version: "3.8"
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=on_lai_sau_2_thang
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3309:3306"
